### ISSUE TITLE
MSBuild integration & avoiding compiling twice

### ISSUE THREAD

**Issue by serard-bimandco** [nenoNaninu/TypedSignalR.Client.TypeScript#101]
Hi,

Thanks for the project.

I want to add a msbuild task on post build success, but then it recompiles the project.
Is there a way to avoid this ?

Thanks.

**Comment by nenoNaninu** [comment]
Please create a small sample repository that I can reproduce if you would like. However, unfortunately, I have little experience with MSBuild task, so I may not know the solution.
