### ISSUE TITLE
Type-only imports should be imported using `import type`

### ISSUE THREAD

**Issue by backfromexile** [nenoNaninu/TypedSignalR.Client.TypeScript#166]
Hi there,

when the TypeScript configuration option `isolatedModules` is active, then the compilation of the generated .ts files fails as they only import types but the imports are not properly marked as such.
Type-only imports should use `import type { Type }` instead of `import { Type }`.
This change should not be an issue for any TypeScript project that uses TypeScript >=3.8.

Because of the issue mentioned above, running my Vue3 project with vite fails with a runtime error like this
`Uncaught SyntaxError: The requested module '/src/_generated/Namespace.Hubs.ts' does not provide an export named 'MyType' (at Namespace.Hubs.ts:6:23)`.

**Comment by backfromexile** [comment]
This is an issue in Tapper as well if I'm not mistaken

**Comment by nenoNaninu** [comment]
Thanks for the issue report. 

I have several projects using `TypedSignalR.Client.TypeScript` with `isolatedModules` is true, and they wrok fine. Perhaps the problem is not caused by the `isolatedModules` setting.

**Comment by backfromexile** [comment]
> Thanks for the issue report.
> 
> I have several projects using `TypedSignalR.Client.TypeScript` with `isolatedModules` is true, and they wrok fine. Perhaps the problem is not caused by the `isolatedModules` setting.

Yeah you are right, I confused this with `preserveValueImports` in combination with `importsNotUsedAsValues`. Vite uses `esbuild` to compile TypeScript code and esbuild requires `import type` because of the mentioned options.

Either way, thanks for merging the PR!
