### ISSUE TITLE
MSB3073:dotnet tsrts --project $(ProjectPath) --output ../$(SolutionName) -asm true --enum NameCamel   Error Code 129	

### ISSUE THREAD

**Issue by 01iePi** [nenoNaninu/TypedSignalR.Client.TypeScript#264]
From 2024/12/02, the  error code129 ocuured. at command, "dotnet tsrts --project $(ProjectPath) --output ../$(SolutionName) -asm true --enum NameCamel"

**Comment by dakoalbeik** [comment]
The `-asm true` option seems to be broken after the last update. I get this error when I include it:

`Error: Unknown option 'a'`

**Comment by 01iePi** [comment]
Thsnaks.
